 context.modules = [
 {   name = libpipewire-module-vban-send
     args = {
         local.ifname = "enp6s0"
         source.ip = "10.1.1.21"
         destination.ip = "10.1.1.20"
         #destination.port = 6980
         #net.mtu = 1500
         #net.ttl = 1
         #net.loop = false
         #sess.min-ptime = 2
         #sess.max-ptime = 20
         sess.name = "mic-vban"
         sess.media = "audio"
         audio.format = "S24LE"
         audio.rate = 48000
         audio.channels = 2
         audio.position = [ FL FR ]
         stream.props = {
	     media.class = "Audio/Sink"
             node.name = "vban-sender"

         }
     }
     #flags = [ nofail ]
}
]
