{ lib, ... }:

# PLACEHOLDER: this host has not been installed yet. Replace this whole file
# with the real hardware-configuration.nix generated by `nixos-generate-config`
# during the actual installation (it will pick up the real disk UUIDs,
# filesystem types, and kernel modules for the VPS provider's image).
{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/00000000-0000-0000-0000-000000000000";
    fsType = "ext4";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
